version: 2.1


# Config 1 : Build APK


jobs:
  build:
    environment:
      DART_SDK: stable
    docker: 
      - image: ghcr.io/cirruslabs/flutter:latest
    steps:
      - checkout
      - run: ls -la

      - run:
          name: Install Dependencies
          command: flutter pub get

      - run:
          name: Update Android SDK
          command: sdkmanager --update
      
      - run:
          name: Build APK
          command: flutter build apk
      - store_artifacts:
          path: build/app/outputs/apk/

