version: 2.1

jobs:
  build:
    environment:
      DART_SDK: stable
    docker: 
      - image: ghcr.io/cirruslabs/flutter:latest
    steps:
      - checkout
      - run: ls -la
      - run: dart run discord_script.dart

