version: 2.1

jobs:
  build:
    environment:
      DART_SDK: stable
    docker: 
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: dart run discord-send-message

