version: 2.1

jobs:
  build:
    environment:
      DART_SDK: stable
    docker: 
      - image: cirruslabs/flutter:3.10.5
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
      - run: dart run discord-send-message

