// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3kzyos80MXeRL-EB-UMg-XvRjZDw2DN8',
    appId: '1:444627893126:web:956f002a0bef72f8170a07',
    messagingSenderId: '444627893126',
    projectId: 'flutter-projet-api',
    authDomain: 'flutter-projet-api.firebaseapp.com',
    storageBucket: 'flutter-projet-api.appspot.com',
    measurementId: 'G-21RNMM2HK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIoiNN7VTGbN-BZ-ei5LQJvIWMKDX5EoQ',
    appId: '1:444627893126:android:13922cc278b3557b170a07',
    messagingSenderId: '444627893126',
    projectId: 'flutter-projet-api',
    storageBucket: 'flutter-projet-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8NsjeyVvHQ4ZUM03AH45vKixzuB0tQQA',
    appId: '1:444627893126:ios:5ff1397ff098216f170a07',
    messagingSenderId: '444627893126',
    projectId: 'flutter-projet-api',
    storageBucket: 'flutter-projet-api.appspot.com',
    iosClientId: '444627893126-nbsmufrmiltre62rqumb2g547f3hm94q.apps.googleusercontent.com',
    iosBundleId: 'com.example.apisOpenData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8NsjeyVvHQ4ZUM03AH45vKixzuB0tQQA',
    appId: '1:444627893126:ios:bcbdaedb935cb19a170a07',
    messagingSenderId: '444627893126',
    projectId: 'flutter-projet-api',
    storageBucket: 'flutter-projet-api.appspot.com',
    iosClientId: '444627893126-slf3pvb6orjtsu4bfatob97i97kpjois.apps.googleusercontent.com',
    iosBundleId: 'com.example.apisOpenData.RunnerTests',
  );
}
